package Mensaje;

public enum MensajeTipo {
	CONEXION,
	CONEXION_CONFIRMADA,
	LISTA_USUARIOS,
	LISTA_USUARIOS_CONFIRMADA,
	PEDIR_EQUIPO,
	EMITIR_EQUIPO,
	CLIENTESERV_PREPARADO,
	SERVCLIENTE_PREPARADO,
	CERRAR_CONEXION,
	CERRAR_CONEXION_CONFIRMADA,
	ARCHIVO_NO_EXIST,
	PEDIR_EQUIPOAUSUARIO 
	//LOS DOS ULTIMOS REVISARLOS
}
